export const Leaderboard=[
    {
        username:"user1",
        mail:"user1@gmail.com",
        score:100,
        img:"src/assets/avatars/characters/men1.png"
    },
    {
        username:"user2",
        mail:"user2@gmail.com",
        score:790,
        img:"src/assets/avatars/characters/men2.png"
    },
    {
        username:"user3",
        mail:"user3@gmail.com",
        score:190,
        img:"src/assets/avatars/characters/men3.png"
    },
    {
        username:"user4",
        mail:"user4@gmail.com",
        score:590,
        img:"src/assets/avatars/characters/women1.png"
    },
    {
        username:"user5",
        mail:"user5@gmail.com",
        score:600,
        img:"src/assets/avatars/characters/women2.png"
    },
    {
        username:"user6",
        mail:"user6@gmail.com",
        score:500,
        img:"src/assets/avatars/characters/women3.png"
    },
    {
        username:"user7",
        mail:"user7@gmail.com",
        score:200,
        img:"src/assets/avatars/characters/char1.png"
    },
    {
        username:"user8",
        mail:"user8@gmail.com",
        score:150,
        img:"src/assets/avatars/characters/char2.png"
    },
    {
        username:"user9",
        mail:"user9@gmail.com",
        score:10,
        img:"src/assets/avatars/characters/men1.png"
    },
    {
        username:"user10",
        mail:"user10@gmail.com",
        score:1000,
        img:"src/assets/avatars/characters/women1.png"
    }
]